# Prometheus configuration for Todo App Web Vitals monitoring
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

# Alertmanager configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]

  # Todo App Backend - Web Vitals metrics
  - job_name: "todo-app-backend"
    scrape_interval: 10s # Scrape more frequently for Web Vitals
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"] # Use host.docker.internal to reach host from Docker
    scrape_timeout: 5s
    honor_labels: true

  # Alternative configuration if running Prometheus natively (not in Docker)
  # - job_name: "todo-app-backend-native"
  #   scrape_interval: 10s
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ["localhost:4000"]
